### ISSUE TITLE
Pine Networking / Page Hosting

### ISSUE THREAD

**Issue by meghanmc** [Haiti-Distributed-Healthcare-System/hdhs#10]
Determine how to use the pine's local network to allow external devices to connect to an application running on a specified port.

Investigate options for creating a consistent address to access the application (i.e. will the users have to enter the IP address manually?)

I should be able to the device as a hotspot, and serve me the application at a constant route / domain / ip.

is nginx or apache complete overkill?

**Comment by bmitchinson** [comment]
https://forum.pine64.org/archive/index.php?thread-4383.html

**Comment by bmitchinson** [comment]
![image](https://user-images.githubusercontent.com/33632286/74094367-b2520380-4aa5-11ea-87e3-8f33133f5f91.png)

The pine wifi module is disabled in all new versions of linux due to security? wha.

What even is "linux 0.7.9"

**Comment by bmitchinson** [comment]
https://raspberrypi.stackexchange.com/questions/82758/eduroam-wpa-enterprise-no-wifi-when-using-wpa-supplicant-conf

https://forum.pine64.org/showthread.php?tid=4383

`sudo iwlist wlan0 scan`

**Comment by bmitchinson** [comment]
https://forum.pine64.org/showthread.php?tid=982

https://forum.pine64.org/showthread.php?tid=7534

https://forum.pine64.org/showthread.php?tid=1578

**Comment by bmitchinson** [comment]
Since the Pine now hosts runs the `npm start` script for create react app and is connected to eduroam, it now can be accessed from over eduroam wireless in react hot-reload mode.

#21 contains some measurable items to make sure using the pine over a pi is worth it.
#10 has more information about what's needed networking wise
#8 has details about configuring the SSD to work.

**Comment by abpwrs** [comment]
Note from in-person convo w/ @bmitchinson :
We don't want anyone to have to type in a static IP address of RockPro64 in order to download the app.
We will need some global redirect or mini DNS resolver type of solution
