### ISSUE TITLE
Create React App

### ISSUE THREAD

**Issue by abpwrs** [Haiti-Distributed-Healthcare-System/hdhs#12]
We will likely want to use the `create-react-app` tool to start the reactjs portion of the project.
```bash
npx create-react-app hdhs
```
@bmitchinson is there a better way to do this if we are building it out as a PWA?

**Comment by bmitchinson** [comment]
Nope! CRA builds a PWA depending on the template you use but, most templates are PWA enabled.

![image](https://user-images.githubusercontent.com/33632286/73855726-18b2f980-47fa-11ea-8249-ac94d0948d84.png)
https://create-react-app.dev/docs/making-a-progressive-web-app/

**Comment by bmitchinson** [comment]
Also don't worry about service worker stuff, we'll be adding that later on.
( I'd like to investigate using easy-peasy for state management if it has good caching options -> https://github.com/ctrlplusb/easy-peasy/issues/424 )

**Comment by bmitchinson** [comment]
We should also make a final decision during standup today (Feb 5th) if we're using the typescript template or the javascript template. I want to use JS to move faster, but TS is probably the right decision. Can't remember which team members have experience with what.
