### ISSUE TITLE
PWA Setup for ReactJS App

### ISSUE THREAD

**Issue by abpwrs** [Haiti-Distributed-Healthcare-System/hdhs#13]
We need to initialize the frontend application to meet all of the requirements of a PWA. 

TODO: fill out this issue with specific tasks that need to be done for the conversion
- [ ] Add `manifest.json`
- [ ] Add ServiceWorkers

NOTE: chrome/chromium has a built-in PWA auditing tool in the inspector.

**Comment by abpwrs** [comment]
https://codelabs.developers.google.com/codelabs/your-first-pwapp/#0

**Comment by abpwrs** [comment]
https://app-manifest.firebaseapp.com/

**Comment by abpwrs** [comment]
Why was this closed?

**Comment by bmitchinson** [comment]
looks like i should have checked the fulfillment criteria more closely my apologies. going forward, those who are assigned the story can be the ones to close it.

i closed it after reviewing that your PR worked fine, and merged it into master. didn't check for full PWA capability
