### ISSUE TITLE
Investigate a simple API "shim" layer to put in front of PostgreSQL

### ISSUE THREAD

**Issue by bmitchinson** [Haiti-Distributed-Healthcare-System/hdhs#18]
Investigate how we'll create simple (maybe automated creation of) REST routes to access PostgreSQL data.
- [ ] Within the container, make sure there are routes at the exposed endpoint to access the PostgreSQL data.
- [ ] This assumes that conversion between FMP and PostgreSQL is complete.

**Comment by bmitchinson** [comment]
https://github.com/PostgREST/postgrest

**Comment by abpwrs** [comment]
I have looked at PostgREST and a couple of GraphQL shims and will write up the documentation on them in the wiki.
