### ISSUE TITLE
UI Design #1 - WireFrame

### ISSUE THREAD

**Issue by abpwrs** [Haiti-Distributed-Healthcare-System/hdhs#2]
Initial estimation: (1 week x 2 people @ 4 hours/week/person | 8 hours)

This is done when we have 
- lo-fi sketches that have been approved by the entire team
- iterated on based on feedback
- available to the team to reference iterations easily
- includes pretty much all anticipated screens for to guide what we need to build in react.
- a page hierarchy site map thing to understand common user flows and what screens connect to which other ones

**Comment by meghanmc** [comment]
update 2-16:

[https://app.zenhub.com/files/217394430/041dc1b1-42e5-472f-ad8b-d5a1e8697638/download](https://app.zenhub.com/files/217394430/041dc1b1-42e5-472f-ad8b-d5a1e8697638/download)

**Comment by meghanmc** [comment]
.png's of each page uploaded to [senior-design-fa19-sp20](https://github.com/Haiti-Distributed-Healthcare-System/senior-design-fa19-sp20/tree/master/design-docs/prototype/images)

**Comment by meghanmc** [comment]
The prototype for Data Entry is complete (essentially replacing the green cards). Prototype is documented in the  [HDHS wiki](https://github.com/Haiti-Distributed-Healthcare-System/hdhs/wiki/Prototype).

Clinician view is currently blocked, at the moment I don't feel that we have enough information to know what info is valuable in those views.
To resolve:
* get info from CHI reps re: what info is valuable to the clinicians
* attempt to start the app for the S19 project to base our design off their clinician view

**Comment by meghanmc** [comment]
Split this into two separate issues, #39 and #40.

This can be closed as wont-do or we can consider this an epic with #39 and #40 as subtasks.

**Comment by bmitchinson** [comment]
Closing this since it's been split into #39 and #40, thank you @meghanmc
