### ISSUE TITLE
Optimize PWA to redirect http -> https

### ISSUE THREAD

**Issue by abpwrs** [Haiti-Distributed-Healthcare-System/hdhs#24]
We should enforce the usage of https. Also, this is the only component that is failing in the lighthouse ci checklist as of the creation of this issue. 

This is done when a device on the same network as the server for the site can connect over https, instead of http. Probably will need to apply for and save a TLS Cert

**Comment by bmitchinson** [comment]
![image](https://user-images.githubusercontent.com/33632286/74545815-23af0d80-4f0f-11ea-9635-e0512e9a53bd.png)

HTTPS will also enable our service worker

**Comment by bmitchinson** [comment]
https://www.npmjs.com/package/serve-https

**Comment by bmitchinson** [comment]
https://github.com/billz/raspap-webgui/issues/513
