### ISSUE TITLE
Investigate hosting a PostgreSQL server within the college

### ISSUE THREAD

**Issue by bmitchinson** [Haiti-Distributed-Healthcare-System/hdhs#26]

**Comment by abpwrs** [comment]
Follow up email sent: 2020/02/12
```
Just following up on the PostgreSQL hosting. Is what we are looking for feasible? 
If so, do you have a time estimate for when this hosting could be live?
```
If we don't hear anything soon we should pursue Linode as our centralized PostgreSQL hosting.

**Comment by bmitchinson** [comment]
Appreciate the follow up, having a university hosted solution would be good to have.
Personally, I'd still prefer linode so that we can spin up a production version of our existing docker container. Seems like PostgreSQL with them would require a lot of back and forth anyway as we need changes made.

**Comment by zainakh** [comment]
Reaching out to Dave at ECS to tell them that we no longer need it.
