### ISSUE TITLE
Get contact information for CHI representative

### ISSUE THREAD

**Issue by zainakh** [Haiti-Distributed-Healthcare-System/hdhs#31]
Currently need to ask about: 
- Clinician views 
- Potential workflow changes involving barcodes (bring convincing support for this)

**Comment by abpwrs** [comment]
- [ ] send email to hans
- [ ] call CHI number directly
- [ ] email chi info address

**Comment by abpwrs** [comment]
Email conversation in `ENGR-HAITI-SD` email account w/ contact information.    
Steve Yagla is acting as our CHI contact for this project.
