### ISSUE TITLE
Get a group organizational email

### ISSUE THREAD

**Issue by bmitchinson** [Haiti-Distributed-Healthcare-System/hdhs#32]
Contact the office of the dean to approve student services making us an organizational account.

**Comment by abpwrs** [comment]
Any timeline on this issue @bmitchinson ? I'd like to reach out to OmniLife and CHI using this email.

**Comment by bmitchinson** [comment]
@abpwrs , going back and forth with Dr. Grosland about it currently, as it requires the deans approval. Hoping that she responds again with approval by end of day.

**Comment by bmitchinson** [comment]
Sat 2/15/2020 6:24 PM
Ben,

I wanted to let you know that I am looking into this.  That is, I am in contact with IT in the college to determine the best approach to getting something set up.
I should hear back from them on Monday.   My apologies for not getting back to you yesterday.

NM Grosland

Sat 2/15/2020 6:45 PM
No worries at all, thanks so much for the speedy response!

**Comment by bmitchinson** [comment]
Dr. Grosland,

Any new news on this?

While I understand it's good to utilize the "in-house" resources available to us, ITS ( its-email@uiowa.edu ticket SR2171063 ) is ready to award the account but just needs your approval.

Apologies if engineering IT would provide some benefits I haven't thought of, and I just need to be a bit more patient 😊

Appreciate your help
- Ben

**Comment by bmitchinson** [comment]
Hello Ben,
Do you have time to discuss this today?  Since this account will be used by others in following semesters, we should setup a staff member as the owner and we should discuss the name of the account.
- Matt

2/19/2020 11:45 AM:
Hey Matt!

Thanks for your help on this, would we be able to meet at 3pm today by chance? I'm free anytime from 3-5.
Otherwise tomorrow anytime from 12:30 to 3:30 would be great.

Thanks
- Ben
