### ISSUE TITLE
Get OmniLifeAi representative information 

### ISSUE THREAD

**Issue by zainakh** [Haiti-Distributed-Healthcare-System/hdhs#33]

**Comment by abpwrs** [comment]
We will likely want to reach out to one of the two UIowa students at OmniLife:     

1.  Eric Pahl 
1.  Anna Seydel

**Comment by abpwrs** [comment]
[Omnilife security brief](https://info.omnilife.ai/hubfs/OmniLife%20Technology%20Security%20Privacy%20Brief%2020190416.pdf)
