### ISSUE TITLE
Schedule Meeting w/ Stakeholders

### ISSUE THREAD

**Issue by abpwrs** [Haiti-Distributed-Healthcare-System/hdhs#42]
Schedule meetings w/ Hans and Steve to work through some of our questions on the views.

Add specific questions in the comments of this ticket, so that the meeting is as productive as possible.

**Comment by bmitchinson** [comment]
I'll add anything I think of to this one ticket
Low Priority: Get svg of logo

**Comment by meghanmc** [comment]
Show Prototype for data entry use case and get feedback.

Clinician view requirements, suggestions.

**Comment by meghanmc** [comment]
Given current extraneous circumstances related to Covid-19, the team does not feel it is valuable at this time to schedule a meeting with CHI representatives for feedback on the prototype. The current prototype will be reviewed with our Sponsor and this issue can be reopened at that time if necessary.
