### ISSUE TITLE
Create React Component: Search Results

### ISSUE THREAD

**Issue by meghanmc** [Haiti-Distributed-Healthcare-System/hdhs#47]
Create a React component that reflects the content of the Search Results page for the data entrant. 

It should contain a list of search results which each show components pulled from the database query (first/last name, picture if available).

See [prototype #5](https://github.com/Haiti-Distributed-Healthcare-System/hdhs/wiki/Prototype#5-search-results) for reference

**Comment by abpwrs** [comment]
This is effectively integrated into #95 

We can reevaluate if need be, but for the time being we could probably close this issue.
