### ISSUE TITLE
Meet with Hans

### ISSUE THREAD

**Issue by zainakh** [Haiti-Distributed-Healthcare-System/hdhs#62]
Schedule a meeting to meet with him by April 13th.

**Comment by abpwrs** [comment]
Discus AWS S3 solution for backups. 
Can we get an AWS S3 account on Hans' credit card or a UIowa ECE credit card?

**Comment by abpwrs** [comment]
Completed components of note:
- Dockerization of the entire application.   
    - Frontend, database, and data API are all hosted in separate containers
    - Well define port configurations allow all of these containers to interact
        
 
- Servable off of a raspberry pi
    - PI acts as its own LAN (hotspot)
    - LAN is password protected and all communications are encrypted (HTTPS)
    - Database and frontend are hosted on the pi simultaneously
    - TODO: test range of network and power consumption




- Frontend application is under development 
    - ?



- Backend transfer from FMP to Postgres is almost done
    - Data transfer is done
    - Primary keys are transferred
    - TODO: foreign key transfer

**Comment by meghanmc** [comment]
Completed:
* Hi-Fi Prototype of Data Entrant view
In Progress:
* React Components for Forms + Unit Testing + Integration Testing

**Comment by abpwrs** [comment]
Meeting completed
