### ISSUE TITLE
Provide Haiti Town Name Database w/ GPS Data

### ISSUE THREAD

**Issue by abpwrs** [Haiti-Distributed-Healthcare-System/hdhs#72]
@hjmjohnson At the beginning of the semester, you mentioned integrating a database of town names and corresponding GPS locations into the patient visit form. Is this data publicly available? If so, where? If not, would you be able to provide us the data you purchased?

**Comment by hjmjohnson** [comment]
Here is a zip of the files.  Updated versions are online.

[HT-Haiti.zip](https://github.com/Haiti-Distributed-Healthcare-System/hdhs/files/4497558/HT-Haiti.zip)

**Comment by abpwrs** [comment]
Thank you

**Comment by hjmjohnson** [comment]
https://www.geonames.org/
