### ISSUE TITLE
FMP -> Postgres Data Validation Sanity Checks

### ISSUE THREAD

**Issue by bmitchinson** [Haiti-Distributed-Healthcare-System/hdhs#77]
As a data analyst 
I want to have sanity checks performed on my data
So that my interpretations of data are accurate

### Acceptance Criteria: 
The following needs to be completed for this story to be "done":
  - [ ] Patients with negative travel in age ... ? Choose most recent age?
  - [ ] Patients with change in gender ... ? Choose most recent gender?

### Notes: 
Helpful information to complete the task, suggestions on how to do so:
  - ...

**Comment by meghanmc** [comment]
Closed by #101
