### ISSUE TITLE
Document using external storage in docker

### ISSUE THREAD

**Issue by abpwrs** [Haiti-Distributed-Healthcare-System/hdhs#8]
Document mounting a new volume and using it in docker.

**Comment by bmitchinson** [comment]
SSD needs the 6A adapter from hans to be supported

**Comment by bmitchinson** [comment]
This got much simpler because it has nothing to do with the RockPro.

https://github.com/Haiti-Distributed-Healthcare-System/hdhs/wiki/Using-Docker#using-an-external-storage-solution
